// src/DashboardContent/DashboardContent.js
import React from 'react';
import { Outlet } from 'react-router-dom';
import './DashboardContent.css'; // Import your CSS file for styling

const DashboardContent = () => {
  return (
    <div className="dashboard-content">
      <div className="header">
        <h2>Welcome to the Dashboard</h2>
        {/* <p>This is the main content of your dashboard. Ghattamaneni Mahesh Babu (born 9 August 1975) is an Indian actor, producer, media personality, and philanthropist who works mainly in Telugu cinema. He has appeared in more than 25 films, and won several accolades including, Nine Nandi Awards, five Filmfare Telugu Awards, four SIIMA Awards, three CineMAA Awards, and one IIFA Utsavam Award. One of the highest-paid Telugu film actors,[1] he also owns the production house G. Mahesh Babu Entertainment.

The younger son of veteran Telugu actor Krishna, Mahesh made his debut as a child artist in a cameo role in Needa (1979), at the age of four,[2] and acted in eight other films as a child artist. He made his debut as a lead actor with Rajakumarudu (1999) which won him the Nandi Award for Best Male Debut.[3] Babu achieved his breakthrough with the supernatural drama Murari (2001), and the action film Okkadu (2003). He went on to act in other commercially successful films such as Arjun (2004), Athadu (2005), Pokiri (2006), Dookudu (2011), Businessman (2012), Seethamma Vakitlo Sirimalle Chettu (2013), Srimanthudu (2015), Bharat Ane Nenu (2018), Maharshi (2019), Sarileru Neekevvaru (2020) and Sarkaru Vaari Paata (2022). Pokiri held the record of being the highest-grossing Telugu film, Maharshi won the National Film Award for Best Popular Film, while Sarileru Neekevvaru, his highest grosser, collected over ₹260 crore at the box office.[4][5]

Referred to in the media and by his fans as Prince, he is one of the most popular actors of Telugu cinema.[6][7] In addition to being an actor, he is a humanitarian and philanthropist – co running the charitable trust and non-profit organisation Heal A Child.[8] He is also associated with Rainbow Hospitals as their goodwill ambassador.[9] He entered into the film exhibition business alongside the late Narayandas Narang of Asian Group with the inauguration of the seven-screen multiplex, AMB cinemas at Gachibowli, Hyderabad.[10] He married actress Namrata Shirodkar in 2005, with whom he has a son and a daughter.[11]

Early life and family
Ghattamaneni Mahesh Babu[12] was born on 9 August 1975[13][better source needed] in a Telugu family in Madras (now Chennai), Tamil Nadu, India.[14] He is the fourth of the five children of Telugu actor Krishna and Indira, after Ramesh Babu, Padmavathi, and Manjula and before Priyadarshini. Their family hails from Burripalem in Guntur district, Andhra Pradesh.[15] Babu spent his childhood mostly in Madras under the care of his maternal grandmother Durgamma and the rest of his family.[16]

He was educated at St. Bede's Anglo Indian Higher Secondary School, Chennai.[14][17] He obtained a bachelor's degree in commerce from the Loyola College, Chennai.[14] Babu and actor Vijay are childhood friends.[18] Babu stated that he had to rely on his memory or conversations with the film directors while delivering dialogues during the dubbing phase of the films.[19]

Acting career
Early career and breakthrough (1979–2003)
At the age of four, Babu visited the sets of the Telugu film Needa (1979) where its director Dasari Narayana Rao shot a few sequences of his as a part of the narrative in the presence of the former's brother Ramesh.[non-primary source needed] Needa marked his debut as a child actor.[citation needed] In 1983, he acted in Poratam (1983) upon being requested by its director Kodi Ramakrishna.[20] He went on to act as a child artist in the films Sankharavam (1987), Bazaar Rowdy (1988), Mugguru Kodukulu (1988) and Gudachari 117 (1989). He played a dual role in the film Koduku Diddina Kapuram (1989). Babu then appeared in Bala Chandrudu (1990), and Anna Thammudu (1990).[20][additional citation(s) needed]

In 1999, Babu made his debut as a lead actor with the romantic comedy Rajakumarudu, directed by K. Raghavendra Rao and co-starring Preity Zinta. The film was commercially successful, and people began referring to him with the title Prince.[21] The film had a 50-day run in 80 centres and a 100-day run in 44 centres. Rajakumarudu collected a share of ₹10.51 crores from Andhra Pradesh.[22] It was dubbed in Hindi as Prince No. 1 and in Tamil as Kaadhal Vennila.[23] The film was again dubbed and released theatrically in Tamil during January 2017 as Ivan Oru Thunichalkaran.[24] For his performance, he received the Nandi Award for Best Male Debut.[25] He starred in two films the following year – Yuvaraju and Vamsi.[citation needed] Following their poor performance at the box office,[citation needed] he starred in Krishna Vamsi's Murari (2001). He regarded Murari an important film in his career and the role he played in it one of his favourites.[26][failed verification][27] Murari was a commercial success[citation needed] and earned him the Nandi Special Jury Award, in addition to his first nomination for the Filmfare Award for Best Actor – Telugu.[25]Idlebrain.com rated the film 3.5/5 stating, "The credit for the success or failure of this film should go to Krishna Vamsi. This film is bound get a little bit of dissent from the viewers of C class areas. But, this film is classic masterpiece for the class audience and highly recommended for the Mahesh and Krishnavamsi fans. This film will be a good fare for the people if they watch this film with no expectations. Just watch this film to experience Krishna Vamsi paint the silver screen with his classic strokes."[28]

Though his 2002 releases Takkari Donga and Bobby performed poorly at the box office,[citation needed] his performance in the former fetched him his second Nandi Special Jury Award.[25] For Takkari Donga A critic from Deccan Chronicle wrote that "A smooth, technically brilliant movie after a considerable time in Telugu, Takari Donga is entertaining and, in spite of its stereotypical pitfalls, is certainly a refreshing break from the deluge of routine love stories".[29] A critic from The Hindu said that "Though it is not new for the Telugu film makers to make cowboy films, this film scores in technical quality, with cinematographer Jayanan Vincent leading in his department. The visual is set against a kind of dusty hue throughout its run, reflecting the wild West".[30] A critic from The Times of India stated that "If you don't mind half a dozen songs slackening the pace of the film Takkari Donga is a complete entertainer".[31]

Babu had two film releases in 2003, the first one being Gunasekhar's Okkadu co-starring Bhumika Chawla, which went on to become the highest grossing Telugu film of the year collecting ₹25–30 crores at the box office.[32] He won his first Filmfare Award for Best Actor – Telugu for his performance in the film.[33] A critic from The Hindu called the film "An opportunity for director Gunasekhar to make a mass movie with an artistic touch. And for Mahesh Babu to assert his versatility".[34] It earned a distributor's share of ₹24.1 crore.[35] The other release was Teja's Nijam co-starring Rakshita. The film was noted for introducing Dolby EX surround system in Telugu cinema.[36] Though the film was a commercial failure,[37] Babu received praise from critics for his performance in the film, with Vijayalaxmi of Rediff.com calling him the only reason to watch the film's second half which she termed "a routine tale of vendetta".[38] He won his first Nandi Award for Best Actor for his performance in the film, in addition to his third nomination for the Filmfare Award for Best Actor – Telugu.[39]Idlebrain Jeevi in his review gave a rating of 3 out of 5 for the movie with concluding remarks "Overall, it's an average film that has chances to become hit because of the Teja's mass-attracting episodes and Mahesh Babu's brilliant portrayal of the character".[40][41]

Mainstream film acclaim and success (2004–2010)
In 2004, Manjula produced his next film,[citation needed] Naani, directed by S. J. Surya co-starring Amisha Patel. While its simultaneously shot Tamil version New featuring a different cast proved to be commercially successful, Naani flopped at the box office.[26][non-primary source needed] He received his third Nandi Special Jury Award for his performance in his next film, Arjun, directed by Gunasekhar and produced by Ramesh.[42] The film released on 18 August 2004[43] and was successful at the box-office.[44] The film was screened at the International Film Festival of India in the mainstream section. This was Keerthi Reddy's final acting performance prior to her retirement from the film industry.[45] He chose to act in Trivikram Srinivas's Athadu (2005), co-starring Trisha Krishnan, whose script had been approved back in 2002 before the production of Naani and Arjun had begun.[46][non-primary source needed] It emerged as one of the highest-grossing films of the year.[47][48] The film proved to be a major boost for Babu's career as he received his fourth nomination for the Filmfare Award for Best Actor – Telugu, in addition to fetching his second Nandi Award for Best Actor for his performance in the role of a hired assassin.[49] The movie collected a share of ₹22 crores at the box office.[citation needed] Idlebrain.com gave it a rating of 3.25/5 and mentioned Mahesh Babu is stylish and brilliant as professional killer.[50]Cinegoer.net gave a review stating, "True the film gives an image of a Hollywood base for the drama. Even the taking, screenplay structure and execution of scenes, less talk and more action.[51]

He then collaborated with Puri Jagannadh in 2006 for the film Pokiri, which was jointly produced by Jagannadh and Manjula.[52] Made on a budget of ₹10 crore and shot within six months,[53] the film grossed over ₹67 crore at the box office and became the highest grossing Telugu film of all time by the end of its run.[54][better source needed] It was screened at the 7th IIFA Awards held in Dubai.[55] It held that position until 2009 when Magadheera pushed it to second place after its nine-day run.[56] He received high praise for his performance, with Y. Sunita Chowdary of The Hindu opining that "Mahesh's understated performance in Pokiri allows him effortlessly to reclaim the title of a star, overshadowing his questionable career choices of late".[52] Jeevi of Idlebrain.com mentioned On a whole, Mahesh Babu's performance in Pokiri itself is worth your ticket and the rest is bonus.[57] He won his second Filmfare Award for Best Actor – Telugu for his performance in the film.[58] That same year, his next film, Sainikudu, co-starring Trisha, was released, but despite much hype, it flopped at the box office.[59] A critic from Rediff.com wrote that "Nonetheless, Sainikudu can be watched at least for its premise of letting the warrior in each individual surface, and the fact that it is done with the idea of motivating people to do something for their fellow humans".[60]

The following year saw Babu acting in the film Athidhi, co-starring Amrita Rao, marking her Telugu debut. The film was produced by Mahesh Babu's's brother Ramesh.[61] UTV Motion Pictures acquired the film's distribution rights for ₹18.5 crore, which became its first Telugu film venture.[62] Jeevi of Idlebrain.com praised the film's first half while criticising the last thirty minutes of the film.[63] In 2008, Babu provided voice-over for the film Jalsa directed by Trivikram Srinivas.[64]

After Athidhi's release, Babu took a break from films for seven months; two months later, he signed Khaleja, but the break was unintentionally extended for two years due to several delays. During this time, Babu's grandmother and his wife Namrata's parents died. Krishna was worried about Babu's career as the film's shoot was delayed for so long.[65] The film deals with illegal-mining in India, and related environmental damage.[66] It marks Babu's return as an actor after a three-year hiatus in his second collaboration with Trivikram after Athadu.

Upon release, Khaleja received mixed reviews from critics and was a commercial failure in India.[67] However, it managed to perform well at the overseas box office becoming the highest grossing Telugu film at that time.[68] Rediff gave a 3 out of 5 rating and noted "The duo of Mahesh-Trivikram delivers a product that is watchable, entertaining with good humour, couple of well-orchestrated action sequences and songs and with a bit to take home as well. It's Mahesh's show all the way, much to the delight of his fans. Mahesh is the soul of the movie, be it his dialogue delivery, his action, his dances or emotions, he is effortless.[69] The film is included in the list of "25 Greatest Telugu Films Of The Decade" by Film Companion.[70]

Stardom and career setback (2011–2014)
In 2011, Babu collaborated with Srinu Vaitla for the film Dookudu, which was inspired in part by the 2003 German tragicomedy film Good Bye, Lenin!.[71] Co-starring Samantha Ruth Prabhu, the film received positive reviews upon release. Dookudu had the largest opening for a Telugu film, and collected a share of ₹10.11 crore and a gross of ₹12.58 crore on the first day of its release.[72] The Los Angeles Times called Dookudu the "biggest hit you've never heard of".[73] For his performance in the film, Babu won his third Filmfare Award for Best Actor – Telugu, his third Nandi Award for Best Actor,[74] and his first SIIMA Award for Best Actor (Telugu).[75][76] The film collected a distributor share of ₹57.4 crore in its lifetime and grossed more than ₹100 crore in its lifetime.[77] After the film's gross crossed the ₹100 crore mark making it the highest-grossing Telugu film of that year. The Income Tax Department officials conducted a raid on Babu's Jubilee Hills residence as he was rumoured of receiving a remuneration of more than ₹12 crore for his next projects.[78] Suresh Kavirayani of The Times of India rated it 4 out of 5 and wrote "Dookudu is a typical Srinu Vytla film with a generous sprinkling of comedy. His narrative manages to keep the audience engaged until the end of the movie. This movie comes as a blessing for not just Mahesh Babu, but also for Tollywood, which is badly in need of a hit, after the recent spate of box office debacles. Srinu Vytla and Mahesh Babu have come out with a winner in Dookudu".[79]Bollywood Life stated "Dookudu has all the elements of a potboiler – the unholy nexus between underworld and politicos, passionate romance, shrill revenge and the glory of father-son relationship. The movie is almost certain to make a box office splash.[80]Sify called the film "entertaining" and wrote "Despite the drawbacks, Dookudu holds the power to lure the crowds, with its commercial values. It is a bonanza to Mahesh Babu's fans and it will not disappoint the family crowds either.[81]

He later played the role of a mafia kingpin with a hidden personal agenda in the film Businessman (2012), co-starring Kajal Aggarwal and directed by Puri Jagannadh.[82] Upon the film's release, he received praise from critics for his performance in the film, with Y. Sunita Chowdary of The Hindu writing, "The film has no frills, no vulgar wastage and the hero is practically in every frame; you hear only his voice, he looks good, sounds good, he also steals the comedian's job. Mahesh plays it straight.".[83] It grossed approximately ₹18.73 crore and collected a share of ₹13.78 crore at the global box office on its first day creating an all-time record in terms of opening day collections.[84] Collecting a share of ₹41 crore at the box office,[85] Businessman became one of the highest grossing Telugu films of the year.[86] He received his seventh nomination for the Filmfare Award for Best Actor – Telugu and his second nomination for the SIIMA Award for Best Actor (Telugu) for his performance in the film.[87][88] By then, Babu was reported to be the second highest-paid actor in South India after Rajinikanth.[89]Indo-Asian News Service (IANS) gave the film 3 out of 5 stars and called Businessman a film for Babu's fans and highlighted Babu's performance and Jagannadh's dialogues as the film's strong points.[90] The film grossed over ₹90 crore in its lifetime at the global box office.[91]


Babu receiving Best Actor – Telugu Award at the 61st Filmfare Awards South from Tamannaah Bhatia for his performance in the film Seethamma Vakitlo Sirimalle Chettu (2013)
Babu then began filming for Srikanth Addala's Seethamma Vakitlo Sirimalle Chettu (2013), whose script Babu had approved during the pre-production phase of Dookudu.[92] Co-starring Daggubati Venkatesh along with Anjali and Samantha Ruth Prabhu, it became the first Telugu multistarrer film to be produced in the last twenty-five years.[93] Released in January 2013, the film became one of the highest grossing Telugu films of the year and marked the completion of Babu's hat-trick of successful films.[94] Sangeetha Devi Dundoo of The Hindu called the film a "delightful family drama with its celebration of family bonds, love and marriage laced with laughter", and Addala "wants to leave his audience with a thought, wants them to reflect on their relationships and overlook skirmishes that can sour family bonds". Dundoo cited Guhan's cinematography as one of the film's highlights, and praised its performances.[95] He won his fourth Filmfare Award for Best Actor – Telugu and his second SIIMA Award for Best Actor (Telugu) for his performance in the film.[96][97] Mahalakshmi Prabhakaran of Daily News and Analysis called the film a "heartwarming watch that has its emotions and underlying message in the right place". Calling Guhan's cinematography and its music wonderful, Prabhakaran also praised the film's cast.[98] Karthik Pasupulate of The Times of India gave Seethamma Vakitlo Sirimalle Chettu 3.5 out of five stars, calling it a "good old fashioned family drama sans the usual masala" and adding that it is "pleasant, well intended, and has some tender moments as well, but does it pack enough entertainment value". Pasupulate praised the performances, calling them understated like the rest of the film.[99] The film collected a distributor share of ₹51.2 crore and was the second-highest-grossing Telugu film of the year.[100] He provided a voice-over for Srinu Vaitla's Baadshah the same year.[101]

Babu had two releases in 2014, the first one being Sukumar's 1: Nenokkadine, an action thriller focusing on a celebrity suffering from hallucinations related to the murder of his parents and the discovery of a special variety of rice. Kriti Sanon played the female lead in this film, marking her acting debut.[102] Made on a budget of around ₹70 crore, 1: Nenokkadine was released amid huge expectations, but received mixed reviews from the critics, turning out to be a box office bomb by incurring a loss of around ₹26–27 crore.[103] However, Babu's performance received praise, with critics calling it one of his best performances.[104][105][106] For his performance, he received his fourth nomination for the SIIMA Award for Best Actor (Telugu).[107] Grossing over $1.32 million,1: Nenokkadine became the fourth-highest-grossing Telugu film in history at the United States box office at that time.[108] Sangeetha Devi Dundoo of The Hindu wrote, "How often do we get to watch a Telugu film where the audience, along with the protagonist and supporting characters, is also required to think and distinguish between events unfolding in real and imaginary spaces?" and called 1 Nenokkadine a "visually stunning" film.[109] Shekhar of Oneindia called the film a "brilliant psychological thriller": "The first half of 1: Nenokkadine is excellent and will impress all classes of audience. A few sentimental scenes slow down the pace of narration in the second half. But the superb climax that lasts for 15 minutes will compensate for it. The viewers will surely walk out of theatre with contented hearts".[110] The film earned a distributor share of about ₹28.9 crore, on a budget of ₹70 crore.[111] The film was commercially unsuccessful at the box office but has gained a cult following over the years for Babu's stellar performance and Sukumar's unique writing. The film is considered one of the "25 Greatest Telugu Films Of The Decade" by Film Companion.[70] The film won three awards from eight nominations at the 4th South Indian International Movie Awards, and two awards at the 11th CineMAA Awards.[112]

The other release, Aagadu, directed by Srinu Vaitla and co-starring Tamannaah Bhatia, flopped at the box office,[113] despite grossing ₹60 crore.The film collected a distributor share of 35.6 crores.[114] Karthik Pasupulate of The Times of India gave the film 3 out of 5 stars and called Aagadu "Dookudu 2.0" in operating system parlance. Pasupulate added that it seems more like a remake of Dookudu with a "much louder Mahesh Babu, more banal jokes, and a few superficial twists in the screenplay", and that the end product is "more slapstick than funny".[115] Rajitha S. of The New Indian Express wrote, "In spite of an entertaining first half, Aagadu fizzles out in the second half and makes for an ordinary affair".[116] He later acknowledged the film's failure and called it a "mistake". He added, "We were very excited during the scripting stage, and had envisioned it very differently. But unfortunately, things panned out differently. Perhaps, it's an error of judgement".[117]

Resurgence and recent work (2015–present)
Babu collaborated with Koratala Siva for the action drama film Srimanthudu (2015) co-starring Shruti Haasan. He co-produced the film under his newly formed banner G. Mahesh Babu Entertainment Pvt. Ltd, marking his first film production venture.[118] He opted to do so to control the film's budget, accepting a share in profits in lieu of remuneration.[119] Released on 7 August 2015, Srimanthudu opened to positive reviews from critics,[120] and he won his fifth Filmfare Award for Best Actor – Telugu for the film,[121] thus marking his resurgence.[122] Sethumadhavan N. of Bangalore Mirror stated, Srimanthudu wouldn't have been as effective if it did not have Mahesh Babu who is at his charming best, adding that he "underplays the emotional scenes, making them a treat to watch".[123] Sangeetha Devi Dundoo of The Hindu called Srimanthudu a star-driven film with a strong plot that's worth a watch". Dundoo further stated, The social consciousness comes coated with commercially viable ingredients and still, makes for an engaging watch.[124] The film was a major commercial success, grossing nearly ₹200 crore globally on a budget of ₹40–70 crore and becoming the second-highest grossing Telugu film of all time and the highest grossing Telugu-language-only film of the time. After the film's release, many actors, bureaucrats and politicians announced plans to develop backward villages and encouraged the adoption of villages in Telangana and Andhra Pradesh.[125] Babu himself has adopted his native village, Burripalem.[126] Babu won third SIIMA award for best actor for his performance in the film.[127] In 2016, he acted in Srikanth Addala's film Brahmotsavam co-starring Kajal Aggarwal, Samantha Ruth Prabhu and Pranitha Subhash. Originally produced as a bi-lingual, the film would've marked Babu's first straight-out Tamil film. However, later on the plan was altered due to its disastrous performance at the Telugu box office and the film wasn't released in Tamil.[128] While the film underperformed at the box office, the Deccan Chronicle stated that Mahesh Babu was its saving grace. The film was criticised by the public, for its lack of a proper story.[129] Y. Sunita Chowdary of The Hindu gave it a 2.5 out of 5 and stated "Brahmotsavam is a confident, grand and sublime title for a noble plot that has been given a superficial treatment. Any joy that comes from the hero or this story is only ephemeral.".[130] Babu stated that this was an error of judgement, where he had picked the wrong director.[131] Brahmotsavam had collected approximately ₹63.70 crore worldwide.[132]

He later appeared in the Telugu-Tamil bilingual Spyder (2017), directed by A. R. Murugadoss, which finally marked his Tamil cinema debut[133] and grossed over ₹118 crores at the box office.[134] The film received mixed reviews, with praise for the cast performances, but criticism for its writing, screenplay and direction.[135] Y. Sunita Chowdary of The Hindu stated that "Spyder starts off well but the director's imagination goes overboard only to turn a purpose ridden plot to a piece of travesty.".[136]Indiaglitz rated the film 2.5 out of 5 and stated "Watch SPYder for Mahesh's genuine efforts and SJ Surya's gritty performance. If you are looking for a fitting duel between the hero and villain you might get disappointed for the film shines only on their respective characters and is let down when it comes to their duel.".[137]

His next film was the political action drama Bharat Ane Nenu (2018), directed by Koratala Siva and co-starring Kiara Advani. In this film, he played the role of a chief minister. It went on to gross more than ₹172 crore, and was second highest-grossing film of that year.[138] Hemanth Kumar of Firstpost wrote "Mahesh Babu and Koratala Siva deliver an intense political drama". Kumar also said, "Siva has shown yet again that there's plenty of drama when a normal guy takes an uncommon path. Bharat might have become the messiah of the state in the story, but it's Mahesh Babu who leaves a long lasting impression in the end. Two big thumbs up for the film. It delivers more than what it promises" giving 4 stars out of 5.[139] Sangeetha Devi Dundoo of The Hindu wrote this promise ticks the right boxes. Bharat Ane Nenu deserves a thumbs up for its well thought out plot and nuanced characters. Keeping us hooked to the narrative are Mahesh Babu, accompanied by Prakash Raj in another winsome and complex role.[140] His performance in the film earned him his tenth nomination for the Filmfare Award for Best Actor – Telugu.His next film, Maharshi (2019) directed by Vamshi Paidipally and co-starring Pooja Hegde collected a total of ₹175 crore worldwide.[141]Maharshi is the third highest grossing Telugu film of 2019 and one of the highest-grossing Telugu films.[142] Hemanth Kumar of Firstpost mentioned the film owes a lot to Mahesh Babu's conviction to pull off his role and he makes you believe in his characterisation so much that it doesn't feel like fiction. His flamboyance in the college sequences and the maturity with which he pulled off the village segments is noteworthy.[143] A critic of Deccan Chronicle too praised cinematography, performances of lead actors and film score, giving a rating of three-and-half out of five.[144] Gabbeta Ranjith Kumar of The Indian Express cited the film as "crowd pleaser", giving a final verdict – "Vamshi Paidipally handles an emotionally intense subject well. But, the director could have paid more attention to Maharshi's run-time. He could have chopped two masala songs which act as speed bumps.".[145]Business Standard too gave a rating of 4 out of 5, writing "The first-half with its quaint college is heartwarming without trying to be excessively cute. Mahesh Babu's transformative performance from arrogant conceit to conscientious farmer is arguably his best to date."[146] The film was awarded the Best Popular Film Providing Wholesome Entertainment at the 68th National Film Awards and Babu won the SIIMA Award for Best Actor – Telugu for his performance.[147][148]

After the release of the film, the concept of weekend farming (also known as weekend agriculture) gained more attention.[149][150][151][152] A new internet challenge. i.e. Agriculture Challenge was started, with several people do farming in the weekends.[153] The Statesman reported that the film has created a social impact on the youth and raised awareness about the issues faced by farmers in the rural heartland.[154] In February 2020, Rajiv Gandhi University of Knowledge Technologies organised the contest "Campus Farming". 250 students of the university participated in this contest.[155]

His 2020 film, Sarileru Neekevvaru, collected ₹260 crores in worldwide box office, becoming one of the highest-grossing Telugu films.[156][157] According to box-office tracking portal Box Office Mojo, the film has grossed US$37.38 million worldwide becoming the second highest grossing Telugu movie of 2020.[158] Hemanth Kumar of Firstpost mentioned Sarileru Neekevvaru packages oodles of humour and action in right measures for Babu to hit the ball out of the park. Everything else is just a bonus or a distraction.[159] Sangeetha Devi of The Hindu wrote "Mahesh Babu's film is a partly entertaining mixed bag."[160] A reviewer of The Hans India rated the film 3/5 stars and wrote, "The movie will be like an eye feast for the audience who have been waiting to see Mahesh Babu in a complete entertaining role".[161]Sify gave the film 3/5 and called it a commercial action-entertainer.[162] His performance in the film earned him his eleventh nomination for the Filmfare Award for Best Actor – Telugu. He next began filming for Sarkaru Vaari Paata, marking his maiden collaboration with director Parasuram in January 2021.[163] The film was released in May 2022 to mixed reviews from critics.Balakrishna Ganeshan of The News Minute gave the film a rating of 3/5 stars and wrote "It is great to see Mahesh Babu shedding his macho image and wooing a woman in the film. Mahesh is a delight to watch in these scenes. His comic timing and dialogue delivery are on point".[164] Sangeetha Devi Dundoo of The Hindu stated "This Mahesh Babu, Keerthy Suresh film gets weighed down by an overdrawn later half".[165] Haricharan Pudipeddi of the Hindustan Times stated "Mahesh Babu offers something fresh in his latest film. If only Keerty Suresh could say the same.[166] Although the screenplay and story received criticism, Babu's performance in the film received praise from various critics including The Hindu,[167] Hindustan Times,[168] India Today,[169] and Pinkvilla.[170] Sarkaru Vaari Paata grossed ₹180–200 crore worldwide in its theatrical run and became the second highest-grossing Telugu film of 2022.[171]

Babu has two upcoming films in various stages production. Babu is reuniting with Trivikram Srinivas for their third collaboration, Guntur Kaaram.[172] It released on 12 January 2024 in theatres worldwide, coinciding with Sankranti.[173] Neeshita Nyayapati of Hindustan Times called it a "bland film" and wrote "Guntur Kaaram feels like a wasted opportunity. The film could've either been a tearjerker or a commercial masala film, but the way it is now, it just hangs in an unsatisfactory limbo. And that's a shame because Mahesh gives the film his all. If only Trivikram could break out of the box he seems to have created for himself."[174] Reviewing the film, Sangeetha Devi Dundoo of The Hindu wrote "Director Trivikram Srinivas and Mahesh Babu's 'Guntur Kaaram' is a stale rehash of old stories".[175] Guntur Kaaram collected a gross of ₹171.5 crore worldwide and emerged as box office bomb.[176][177] He is also committed to star in S. S. Rajamouli's untitled film which is expected to begin its production in 2024. The film is touted to be a jungle adventure set in Africa.[178]

In the media

Babu at Selvandhan Audio Launch
Babu is considered one of the most popular actors in Telugu cinema.[179] He is widely referred in the media as "Superstar of Tollywood",[180] and "Prince Mahesh Babu".[181] Hemanth Kumar C. R. of Vogue felt that Murari (2001), Okkadu (2003), Arjun (2004), Athadu (2005), Pokiri (2006), Khaleja (2010), Dookudu (2011),Businessman (2012), Seethamma Vakitlo Sirimalle Chettu (2013), 1: Nenokkadine (2014), Srimanthudu (2015) and Bharat Ane Nenu (2018), Maharshi (2019), Sarileru Neekevvaru (2020) are the films that made Mahesh Babu, a superstar in the film industry.[182]

His popularity has been documented in several Telugu films such as Ashta Chamma (2008),[183] Kiraak (2014),[184] and Superstar Kidnap (2015).[185][weasel words] He joined Twitter in April 2010 and has 13 million followers as of April 2023.[186][relevant?]

He was ranked twelfth on the Times' 50 Most Desirable Men in India for the year 2010,[187] fifth in 2011,[188] and second in 2012.[189] He climbed to the first position of the same list for the year 2013, beating the likes of Hrithik Roshan, Salman Khan, and Shah Rukh Khan.[190] He stood at sixth place on the same list for the year 2014,[191] sixth in 2015,[192] seventh in 2016,[193] and sixth in 2017.[194] He was then added to the Forever Desirable list along with Salman Khan, Shah Rukh Khan, Aamir Khan, Akshay Kumar, and Hrithik Roshan.[195]

Babu is an ambassador for about three dozen Indian brands.[196][197] In 2007, he signed a five-year endorsement deal with the cola company Thums Up to replace Chiranjeevi as its brand ambassador in Andhra Pradesh;[198] after which, he was replaced by Akshay Kumar as the national brand ambassador across India.[199] He endorsed brands such as UniverCell Mobile Store,[200] Navratna Oil,[201] Amrutanjan,[202] Provogue,[203] ITC Vivel,[204] Jos Alukkas,[205] Idea Cellular,[206] Santoor Soap,[207] South India Shopping Mall,[208] Royal Stag,[209] Rainbow Hospitals,[210] TVS Motor Company,[211] Mahindra Tractors,[212] Paragon footwear,[213] and Tata Sky in South India.[214] He was signed as the brand ambassador of Intex Mobiles in August 2015 for one year.[215] He also promotes the real estate firm Ramakrishna Venuzia.[216] Babu commands a figure of ₹2.5–3 crore per endorsement per annum, thus earning around ₹30 crore per annum as a brand ambassador.[217][weasel words] In 2016, he was signed as the brand ambassador of YuppTV,[218] and AbhiBus.[219] In February 2018, he was signed as the brand ambassador for Protinex.[220] Some of the other brands he endorses, or had endorsed previously, include Chennai Silks,[221] Sai Surya Developers,[222] Close-Up,[223] Gold Winner,[224] Denver Deodorant,[225] Lloyd AC,[226] Flipkart,[227] Helo app,[228] Byju's,[229] CarDekho,[230] Jeep India,[231] Whitehat Junior,[232] Lloyd Refrigerators,[233] Jeevan Saathi,[234] Health OK Tablets,[235] Big C Mobiles,[236] Pan Bahar Elaichi,[237] Mountain Dew,[238] Bambino foods,[239] and Everest Spices.[240] Otto[241] Overall, he has endorsed 41 brands thus far.[citation needed] He has also shot a couple of unique concept videos for Zee Telugu to promote their upcoming TV shows.[242][243] In 2022, he ended his association with Thums Up.[244] The same year, he faced criticism for endorsing the brand Pan Bahar Elaichi, after the statement "Bollywood cannot afford me" he made during a promotional event of Major (2022).[245]

Babu has also supported AIG Hospitals' "End Corona Campaign", which was aimed at creating awareness about the COVID-19 vaccine.[246] It was one of the world's largest virtual awareness campaigns on the COVID-19 vaccine.[247]

Babu stood in 31st place on Forbes India's Celebrity 100 list for the year 2012, with annual earnings of ₹42.25 crore.[248] He slipped to 54th place on the same list for the year 2013, with his annual earnings dropping to ₹28.96 crore.[249] In the following year, he climbed to the 30th position with an annual earning figure of ₹51 crore.[250] In 2015, he placed 36th, the highest ranking Telugu celebrity, with an income of ₹51 crore.[251] He was placed 37th, 33rd and 54th consecutively in the years leading up to 2019 with an annual earning of ₹35 crore.[252]

In 2019, his wax statue was unveiled in Madame Tussauds Singapore.[253] Hindustan Times reported that he was the first Telugu actor to get a wax statue at Madame Tussauds.[254] He was also the first Indian actor whose wax statue was flown back for a day for unveiling at his hometown.[255]

Personal life
Family
Babu married his co-star Namrata Shirodkar on 10 February 2005 at the Marriott Hotel, Mumbai during the shooting of Athadu (2005).[256] The couple's first child was born on 31 August 2006 at the Global Hospital in Hyderabad.[257] The boy was named Gautam.[258] On 20 July 2012, Shirodkar gave birth to a girl whom they named Sitara.[259] Before her delivery, they preserved her stem cells using stem cell banking to ensure a better immunity level.[260]

Babu is the fourth child in a family of five children. His elder brother Ramesh Babu was a film producer and was also an actor. Mahesh Babu's eldest sister Padmavathi is married to Galla Jayadev, an industrialist and Member of the Indian Parliament from the Telugu Desam Party.[261] His elder sister Manjula is a film producer, director, and an actress.[citation needed] Priyadarshini, his younger sister, is married to Sudheer Babu, who later made his debut as an actor in Telugu cinema.[262]

Telugu actress and filmmaker Vijaya Nirmala was Babu's step-mother; actor Naresh is his step-brother.[263]

Philanthropy
Babu gives 30% of his annual income to charities, and most of his philanthropic activities are unpublicised because he prefers them to be so.[264] He joined Farhan Akhtar's Men Against Rape and Discrimination (MARD) campaign in August 2013 and lent his voice to the Telugu version of a poem written by Javed Akhtar.[265] He was signed in 2013 as the goodwill ambassador of Heal-a-child Foundation, a non-profit organisation that offers financial support to the parents of terminally ill children to help with the cost of medical treatment.[266] In October 2014, he donated ₹25 lakh to a relief fund run by the chief minister of Andhra Pradesh for reconstruction of areas destroyed during Cyclone Hudhud. Krishna and Vijaya Nirmala later donated ₹25 lakh to the fund.[267]

Jayadev announced in February 2015 that Babu would adopt Krishna's native village Burripalem, a minor panchayat in Tenali, and would address basic needs of the community such as potable drinking water and better roads and drainage systems.[268] Later, Namrata Shirodkar was quoted saying that they had adopted Siddapur village in Mahbubnagar district upon consultation with Telangana's Rural Development minister K. T. Rama Rao.[269]

Legal issues
In September 2004, Babu and director Gunasekhar attended a rally organised by his fans at Warangal for the promotional activities of Arjun. He and his fans allegedly raided two video libraries and assaulted their owners who were circulating unauthorised CDs of the film. Cases under IPC section 448 (criminal trespass), section 427 (mischief) and section 366 (kidnap) were registered on him, who was the principal accused, and five others.[270] Later, a delegation from the Telugu film industry, including his father Krishna, Chiranjeevi, Nagarjuna, Allu Aravind and D. Suresh Babu, approached the then chief minister Y. S. Rajasekhara Reddy to intervene in this case. Regarding the issue, Babu said that while cases were booked against him on "the basis of wrong information," not a single case had been booked against the person dealing in bootlegged CDs, which he found the "funniest" thing.[271] Actor Pawan Kalyan openly supported Babu throughout the episode.[272] Babu surrendered in the district court in September 2004 and appeared before the court again in April 2006. Babu and the others were exonerated after the final hearing in July 2006.[273]</p> */}
      </div>

      <div className="main-content">
        {/* Render nested routes */}
        <Outlet />
      </div>
    </div>
  );
};

export default DashboardContent;
